# Basic Python Code:


## Using Basic Arithmetic Operators on two numbers:

In [1]:
a = int(input('Enter a number:'))
b = int(input('Enter a number:'))
print(a,b)

Enter a number:5
Enter a number:4
5 4


In [2]:
print('sum:')
print(a + b)
print('difference:')
print(a - b)
print('product:')
print(a * b)
print('division:')
print(a / b)

sum:
9
difference:
1
product:
20
division:
1.25


## Creating two arrays and performing operations.

In [3]:
from numpy import random
x = random.randint(10, size=(5))
print(x)

y = random.randint(10, size=(5))
print(y)

print('sum:')
print(x + y)
print('difference:')
print(x - y)
print('product:')
print(x * y)
print('division:')
print(x / y)

[5 8 7 9 8]
[1 6 4 3 7]
sum:
[ 6 14 11 12 15]
difference:
[4 2 3 6 1]
product:
[ 5 48 28 27 56]
division:
[5.         1.33333333 1.75       3.         1.14285714]


## Using loops to perform operations.

In [4]:
from numpy import random
import numpy as np
x = random.randint(10, size=(5))
y = random.randint(10, size=(5))
z = np.array([])
for i in range(1,6):
    a = x[i-1] + y[i-1]
    z = np.append(z ,[a], axis = 0)
print('sum:')
print(z)

for i in range(1,6):
    a = x[i-1] - y[i-1]
    z = np.append(z ,[a], axis = 0)
print('difference:')
print(z)

for i in range(1,6):
    a = x[i-1] * y[i-1]
    z = np.append(z ,[a], axis = 0)
print('product:')
print(z)

for i in range(1,6):
    a = x[i-1] / y[i-1]
    z = np.append(z ,[a], axis = 0)
print('division:')
print(z)

sum:
[ 5. 14. 16.  4. 13.]
difference:
[ 5. 14. 16.  4. 13.  1.  4. -2.  0. -5.]
product:
[ 5. 14. 16.  4. 13.  1.  4. -2.  0. -5.  6. 45. 63.  4. 36.]
division:
[ 5.         14.         16.          4.         13.          1.
  4.         -2.          0.         -5.          6.         45.
 63.          4.         36.          1.5         1.8         0.77777778
  1.          0.44444444]
